// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

package example

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateWidgetRequest struct {
	// @validate: required
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" validate:"required"`
	// @validate: required,gte=21,lte=121
	Age int32 `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty" validate:"required,gte=21,lte=121"`
	// @validate: required,email
	Email string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty" validate:"required,email"`
	// @validate: required,e164
	PhoneNumber string `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty" validate:"required,e164"`
	// @validate: dive,required
	Attributes           []string `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" validate:"dive,required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWidgetRequest) Reset()         { *m = CreateWidgetRequest{} }
func (m *CreateWidgetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateWidgetRequest) ProtoMessage()    {}
func (*CreateWidgetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{0}
}

func (m *CreateWidgetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWidgetRequest.Unmarshal(m, b)
}
func (m *CreateWidgetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWidgetRequest.Marshal(b, m, deterministic)
}
func (m *CreateWidgetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWidgetRequest.Merge(m, src)
}
func (m *CreateWidgetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateWidgetRequest.Size(m)
}
func (m *CreateWidgetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWidgetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWidgetRequest proto.InternalMessageInfo

func (m *CreateWidgetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateWidgetRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *CreateWidgetRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateWidgetRequest) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *CreateWidgetRequest) GetAttributes() []string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type CreateWidgetReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateWidgetReply) Reset()         { *m = CreateWidgetReply{} }
func (m *CreateWidgetReply) String() string { return proto.CompactTextString(m) }
func (*CreateWidgetReply) ProtoMessage()    {}
func (*CreateWidgetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{1}
}

func (m *CreateWidgetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateWidgetReply.Unmarshal(m, b)
}
func (m *CreateWidgetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateWidgetReply.Marshal(b, m, deterministic)
}
func (m *CreateWidgetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateWidgetReply.Merge(m, src)
}
func (m *CreateWidgetReply) XXX_Size() int {
	return xxx_messageInfo_CreateWidgetReply.Size(m)
}
func (m *CreateWidgetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateWidgetReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateWidgetReply proto.InternalMessageInfo

func (m *CreateWidgetReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetWidgetRequest struct {
	// @validate: required,uuid4
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" validate:"required,uuid4"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWidgetRequest) Reset()         { *m = GetWidgetRequest{} }
func (m *GetWidgetRequest) String() string { return proto.CompactTextString(m) }
func (*GetWidgetRequest) ProtoMessage()    {}
func (*GetWidgetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{2}
}

func (m *GetWidgetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWidgetRequest.Unmarshal(m, b)
}
func (m *GetWidgetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWidgetRequest.Marshal(b, m, deterministic)
}
func (m *GetWidgetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWidgetRequest.Merge(m, src)
}
func (m *GetWidgetRequest) XXX_Size() int {
	return xxx_messageInfo_GetWidgetRequest.Size(m)
}
func (m *GetWidgetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWidgetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetWidgetRequest proto.InternalMessageInfo

func (m *GetWidgetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetWidgetReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  string   `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Attributes           []string `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWidgetReply) Reset()         { *m = GetWidgetReply{} }
func (m *GetWidgetReply) String() string { return proto.CompactTextString(m) }
func (*GetWidgetReply) ProtoMessage()    {}
func (*GetWidgetReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_15a1dc8d40dadaa6, []int{3}
}

func (m *GetWidgetReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWidgetReply.Unmarshal(m, b)
}
func (m *GetWidgetReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWidgetReply.Marshal(b, m, deterministic)
}
func (m *GetWidgetReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWidgetReply.Merge(m, src)
}
func (m *GetWidgetReply) XXX_Size() int {
	return xxx_messageInfo_GetWidgetReply.Size(m)
}
func (m *GetWidgetReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWidgetReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetWidgetReply proto.InternalMessageInfo

func (m *GetWidgetReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetWidgetReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetWidgetReply) GetAge() string {
	if m != nil {
		return m.Age
	}
	return ""
}

func (m *GetWidgetReply) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetWidgetReply) GetAttributes() []string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateWidgetRequest)(nil), "CreateWidgetRequest")
	proto.RegisterType((*CreateWidgetReply)(nil), "CreateWidgetReply")
	proto.RegisterType((*GetWidgetRequest)(nil), "GetWidgetRequest")
	proto.RegisterType((*GetWidgetReply)(nil), "GetWidgetReply")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor_15a1dc8d40dadaa6) }

var fileDescriptor_15a1dc8d40dadaa6 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0xd1, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x07, 0xf0, 0xe6, 0x4b, 0xc8, 0xb4, 0xc6, 0x76, 0xec, 0x21, 0xf4, 0x20, 0x71, 0xbd, 0xe4,
	0xb4, 0xa0, 0xde, 0xf4, 0xa6, 0x88, 0x37, 0x0f, 0xf1, 0x20, 0x78, 0x91, 0x4d, 0x33, 0xc4, 0x85,
	0x7c, 0xb9, 0xdd, 0x88, 0x82, 0xe0, 0x4b, 0xf8, 0xc0, 0xe2, 0xa6, 0x4a, 0xd2, 0x16, 0xbc, 0x4d,
	0x26, 0xc3, 0xf2, 0xff, 0xcd, 0xc0, 0x3e, 0xbd, 0x89, 0xb2, 0x29, 0x88, 0x37, 0xaa, 0xd6, 0x35,
	0xfb, 0xb2, 0xe0, 0xf0, 0x5a, 0x91, 0xd0, 0xf4, 0x20, 0xb3, 0x9c, 0x74, 0x42, 0x2f, 0x2d, 0xad,
	0x34, 0x22, 0xb8, 0x95, 0x28, 0x29, 0xb4, 0x22, 0x2b, 0xf6, 0x13, 0x53, 0xe3, 0x14, 0x1c, 0x91,
	0x53, 0x68, 0x47, 0x56, 0xec, 0x25, 0x3f, 0x25, 0xce, 0xc1, 0xa3, 0x52, 0xc8, 0x22, 0x74, 0xcc,
	0x58, 0xf7, 0x81, 0xc7, 0x30, 0x69, 0x9e, 0xeb, 0x8a, 0x9e, 0xaa, 0xb6, 0x4c, 0x49, 0x85, 0xae,
	0xf9, 0x39, 0x36, 0xbd, 0x3b, 0xd3, 0xc2, 0x23, 0x00, 0xa1, 0xb5, 0x92, 0x69, 0xab, 0x69, 0x15,
	0x7a, 0x91, 0x13, 0xfb, 0x49, 0xaf, 0xc3, 0x4e, 0x60, 0x36, 0x4c, 0xd5, 0x14, 0xef, 0x18, 0x80,
	0x2d, 0xb3, 0x75, 0x22, 0x5b, 0x66, 0x8c, 0xc1, 0xf4, 0x96, 0xf4, 0x30, 0xf7, 0xe6, 0xcc, 0x07,
	0x04, 0xbd, 0x99, 0x1d, 0xaf, 0xfc, 0x49, 0xed, 0x6d, 0x69, 0xa7, 0x1a, 0x4a, 0xdd, 0xbe, 0xf4,
	0x1f, 0xc6, 0xd9, 0x27, 0x04, 0x37, 0xdd, 0xba, 0xef, 0x49, 0xbd, 0xca, 0x25, 0xe1, 0x05, 0x4c,
	0x96, 0x3d, 0x18, 0xce, 0xf9, 0x8e, 0xed, 0x2f, 0x90, 0x6f, 0xe9, 0xd9, 0x08, 0x4f, 0xc1, 0xcf,
	0x7f, 0x2d, 0x38, 0xe3, 0x9b, 0xf6, 0xc5, 0x01, 0x1f, 0x52, 0xd9, 0xe8, 0x6a, 0xfc, 0xe8, 0xf3,
	0xcb, 0xf5, 0xc5, 0xd3, 0x3d, 0x73, 0xf2, 0xf3, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x57, 0x46,
	0x78, 0xaf, 0x03, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleServiceClient is the client API for ExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleServiceClient interface {
	CreateWidget(ctx context.Context, in *CreateWidgetRequest, opts ...grpc.CallOption) (*CreateWidgetReply, error)
	GetWidget(ctx context.Context, in *GetWidgetRequest, opts ...grpc.CallOption) (*GetWidgetReply, error)
}

type exampleServiceClient struct {
	cc *grpc.ClientConn
}

func NewExampleServiceClient(cc *grpc.ClientConn) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) CreateWidget(ctx context.Context, in *CreateWidgetRequest, opts ...grpc.CallOption) (*CreateWidgetReply, error) {
	out := new(CreateWidgetReply)
	err := c.cc.Invoke(ctx, "/ExampleService/createWidget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exampleServiceClient) GetWidget(ctx context.Context, in *GetWidgetRequest, opts ...grpc.CallOption) (*GetWidgetReply, error) {
	out := new(GetWidgetReply)
	err := c.cc.Invoke(ctx, "/ExampleService/getWidget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServiceServer is the server API for ExampleService service.
type ExampleServiceServer interface {
	CreateWidget(context.Context, *CreateWidgetRequest) (*CreateWidgetReply, error)
	GetWidget(context.Context, *GetWidgetRequest) (*GetWidgetReply, error)
}

// UnimplementedExampleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedExampleServiceServer struct {
}

func (*UnimplementedExampleServiceServer) CreateWidget(ctx context.Context, req *CreateWidgetRequest) (*CreateWidgetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWidget not implemented")
}
func (*UnimplementedExampleServiceServer) GetWidget(ctx context.Context, req *GetWidgetRequest) (*GetWidgetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWidget not implemented")
}

func RegisterExampleServiceServer(s *grpc.Server, srv ExampleServiceServer) {
	s.RegisterService(&_ExampleService_serviceDesc, srv)
}

func _ExampleService_CreateWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).CreateWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExampleService/CreateWidget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).CreateWidget(ctx, req.(*CreateWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExampleService_GetWidget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).GetWidget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExampleService/GetWidget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).GetWidget(ctx, req.(*GetWidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "createWidget",
			Handler:    _ExampleService_CreateWidget_Handler,
		},
		{
			MethodName: "getWidget",
			Handler:    _ExampleService_GetWidget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example.proto",
}
